- train_simclr_imgnt_u90_tr100.yaml
- train_simclr_imgnt_u90_tr200.yaml
- train_simclr_imgnt_u90_tr300.yaml
- train_simclr_imgnt_u90_tr500.yaml
- train_simclr_imgnt_u90_tr1000.yaml

- train_suncet_imgnt_u90_tr100.yaml
- train_suncet_imgnt_u90_tr200.yaml
- train_suncet_imgnt_u90_tr300.yaml
- train_suncet_imgnt_u90_tr500.yaml
