data:
  dataset: imagenet_fine_tune
  normalize: false
  num_classes: 1000
  unlabeled_frac: 0.9
  root_path: /datasets01/
  image_folder: imagenet_full_size/061417/
  subset_path: imagenet_subsets/
logging:
  folder: logging/
  pretrain_path: simclr-imgnt-tr100-best.pth.tar
  write_tag: simclr-imgnt-tr100-best
meta:
  copy_data: false
  device: cuda:0
  load_checkpoint: false
  model_name: resnet50
  training: true
  use_fp16: false
