criterion:
  classes_per_batch: 0
  gather_tensors: true
  supervised_batch_size: 0
  temperature: 0.1
  unsupervised_batch_size: 64
data:
  color_jitter: 1.0
  dataset: imagenet
  image_folder: imagenet_full_size/061417/
  normalize: false
  root_path: /datasets01/
  subset_path: imagenet_subsets
  unlabeled_frac: 0.9
logging:
  folder: logging/
  read_checkpoint: simclr-imgnt-tr100-latest.pth.tar
  write_tag: simclr-imgnt-tr100
meta:
  copy_data: false
  device: cuda:0
  load_checkpoint: false
  model_name: resnet50
  training: true
  use_fp16: false
optimization:
  epochs: 100
  lr: 4.8
  start_lr: 0.6
  supervised_epochs: 0
